version: '3'
services:
  python:
    # image: python:3.6
    tty: true
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./mysite:/mysite
    
    ports:
      - 8000:8000
    
   
